//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VpassSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string ConactNumber { get; set; }
        public string FirmName { get; set; }
        public string Address { get; set; }
        public string TinNo { get; set; }
        public string PanNo { get; set; }
        public string BankIFSC { get; set; }
        public string BankAccNumber { get; set; }
    }
}
